### ISSUE TITLE
Undefined index in class-wc-checkout.php

### ISSUE THREAD

**Issue by MyEmpireOfDuctTape** [codelight-eu/woocommerce-lhv-hire-purchase#2]
Fix for this:
In  WooCommerceOrderHandler.php, line 81
change
        return [
            'result' => 'success',
            'url'    => $request->getRequestUrl(),
            'data'   => $fields,
        ];

to

 return [
            'result' => 'success',
            'redirect'    => $request->getRequestUrl(),
            'data'   => $fields,
        ];

**Comment by indrek-k** [comment]
Thanks, will investigate soon!
